In [1]:
import json

In [10]:
with open('predict/final/eval/binary_predict.jsonl','r') as f:
    binary_predict = f.readlines()
    binary_predict = [json.loads(e) for e in binary_predict]
sum([e['true'] for e in binary_predict]) / len(binary_predict)

0.8268382352941176

In [11]:
with open('predict/final/eval/ner_predict.jsonl','r') as f:
    ner_predict = f.readlines()
    ner_predict = [json.loads(e) for e in ner_predict]
sum([e['true'] for e in ner_predict]) / len(ner_predict)

0.8319852941176471

In [12]:
with open('predict/final/eval/co_num_predict.jsonl','r') as f:
    co_num_predict = f.readlines()
    co_num_predict = [json.loads(e) for e in co_num_predict]
sum([e['true'] for e in co_num_predict]) / len(co_num_predict)

0.8768382352941176

In [13]:
with open('predict/final/eval/seq_predict.jsonl','r') as f:
    seq_predict = f.readlines()
    seq_predict = [json.loads(e) for e in seq_predict]
sum([e['true'] for e in seq_predict]) / len(seq_predict)

0.8830882352941176

In [14]:
with open('predict/final/eval/ensemble_predict.jsonl','r') as f:
    ensemble_predict = f.readlines()
    ensemble_predict = [json.loads(e) for e in ensemble_predict]
sum([e['true'] for e in ensemble_predict]) / len(ensemble_predict)

0.925

In [16]:
len(ensemble_predict)

2720

In [36]:
[i for i in range(len(ensemble_predict)) if ensemble_predict[i]['true'] == True and seq_predict[i]['true'] == False and co_num_predict[i]['true'] == False and binary_predict[i]['true'] == False]

[788, 993, 1155, 1948]

In [17]:
10 / 2720

0.003676470588235294

In [41]:
seq_predict[441]

{'translation': '你看，天上的鸟儿都自由自在地飞翔。',
 'choices': ['翩翻仰飞鸟', '仰视飞鸟落', '下视飞鸟背', '仰视百鸟飞'],
 'answer': 3,
 'scores': [0.19398722670869567,
  0.20510580491717548,
  0.32825672489071406,
  0.27265024348341493],
 'predict': 2,
 'true': False}

In [34]:
binary_predict[441]

{'translation': '你看，天上的鸟儿都自由自在地飞翔。',
 'choices': ['翩翻仰飞鸟', '仰视飞鸟落', '下视飞鸟背', '仰视百鸟飞'],
 'answer': 3,
 'model_output': {'下视': [0.38646732419528024, 0.6135326758047198],
  '翩翻': [0.47833101535795153, 0.5216689846420485],
  '仰飞鸟': [0.7036007677502361, 0.29639923224976383],
  '仰视': [0.3867027673488945, 0.6132972326511055],
  '百鸟飞': [0.7206128541035892, 0.2793871458964107],
  '飞鸟落': [0.9095912876244866, 0.09040871237551344],
  '飞鸟背': [0.8970898359274445, 0.10291016407255546]},
 'scores': [0.2582129014445311,
  0.2303090660156364,
  0.23326124928599934,
  0.2782167832538333],
 'predict': 3,
 'true': True}

In [ ]:
[[0.2151,
   0.2222,
   0.019755132496356964,
   0.01903093233704567,
   0.02172483503818512],
  [0.8165768384933472,
   0.7930786609649658,
   0.09453681111335754,
   0.1201082095503807,
   0.13352201879024506],
  [0.05685175582766533,
   0.0479537732899189,
   0.013241013512015343,
   0.01512275729328394,
   0.016727933660149574],
  [0.9616498351097107,
   0.9586278200149536,
   0.9806236624717712,
   0.9780905246734619,
   0.9768726825714111]]

In [47]:
ner_predict[441]

{'translation': '你看，天上的鸟儿都自由自在地飞翔。',
 'choices': ['翩翻仰飞鸟', '仰视飞鸟落', '下视飞鸟背', '仰视百鸟飞'],
 'answer': 3,
 'model_output': [[0.21516215801239014,
   0.22229371964931488,
   0.019755132496356964,
   0.01903093233704567,
   0.02172483503818512],
  [0.8165768384933472,
   0.7930786609649658,
   0.09453681111335754,
   0.1201082095503807,
   0.13352201879024506],
  [0.05685175582766533,
   0.0479537732899189,
   0.013241013512015343,
   0.01512275729328394,
   0.016727933660149574],
  [0.9616498351097107,
   0.9586278200149536,
   0.9806236624717712,
   0.9780905246734619,
   0.9768726825714111]],
 'scores': [0.18611535340172894,
  0.18629810549519557,
  0.18611528239507272,
  0.44147125870800297],
 'predict': 3,
 'true': True}

In [46]:
import numpy as np
t = np.array(ner_predict[441]['model_output'])
np.set_printoptions(precision=4)
print(t)

[[0.2152 0.2223 0.0198 0.019  0.0217]
 [0.8166 0.7931 0.0945 0.1201 0.1335]
 [0.0569 0.048  0.0132 0.0151 0.0167]
 [0.9616 0.9586 0.9806 0.9781 0.9769]]


In [48]:
seq_predict[993]

{'translation': '我寄上一封简短的书信，信中每一行字上都浸透了我的眼泪。',
 'choices': ['一行书寄千行泪', '一封书堕数行泪', '一行书信千行泪', '寄得一行书信无'],
 'answer': 2,
 'scores': [0.1756034668538244,
  0.4720922529034535,
  0.17691259067288037,
  0.17539168956984175],
 'predict': 1,
 'true': False}

In [49]:
for c_id in range(4):
    print(seq_predict[993]['choices'][c_id],'\t',seq_predict[993]['scores'][c_id])

一行书寄千行泪 	 0.1756034668538244
一封书堕数行泪 	 0.4720922529034535
一行书信千行泪 	 0.17691259067288037
寄得一行书信无 	 0.17539168956984175


In [39]:
binary_predict[993]

{'translation': '我寄上一封简短的书信，信中每一行字上都浸透了我的眼泪。',
 'choices': ['一行书寄千行泪', '一封书堕数行泪', '一行书信千行泪', '寄得一行书信无'],
 'answer': 2,
 'model_output': {'数行泪': [0.1517243025333168, 0.8482756974666832],
  '书信': [0.11687159285511464, 0.8831284071448854],
  '书堕': [0.6825764399623817, 0.3174235600376183],
  '一封': [0.03274459146331886, 0.9672554085366811],
  '千行泪': [0.42108949164512877, 0.5789105083548712],
  '一行': [0.4599225263099961, 0.5400774736900039],
  '寄得': [0.22526594478466486, 0.7747340552153351],
  '书信无': [0.7750014838185085, 0.22499851618149155],
  '书寄': [0.23256756637210407, 0.7674324336278959]},
 'scores': [0.19560745114009995,
  0.2502959708454361,
  0.21959958594899853,
  0.33449699206546546],
 'predict': 3,
 'true': False}

In [56]:
for k in binary_predict[993]['model_output']:
    print(k,'\t','{:.4f}'.format(binary_predict[993]['model_output'][k][-1]))

数行泪 	 0.8483
书信 	 0.8831
书堕 	 0.3174
一封 	 0.9673
千行泪 	 0.5789
一行 	 0.5401
寄得 	 0.7747
书信无 	 0.2250
书寄 	 0.7674


In [40]:
ner_predict[993]

{'translation': '我寄上一封简短的书信，信中每一行字上都浸透了我的眼泪。',
 'choices': ['一行书寄千行泪', '一封书堕数行泪', '一行书信千行泪', '寄得一行书信无'],
 'answer': 2,
 'model_output': [[0.7826950550079346,
   0.8017566800117493,
   0.6719909310340881,
   0.6844205260276794,
   0.828391969203949,
   0.7786412835121155,
   0.7616693377494812],
  [0.9829880595207214,
   0.9788326025009155,
   0.5002279877662659,
   0.5091439485549927,
   0.9902712106704712,
   0.9903371334075928,
   0.990261971950531],
  [0.9637319445610046,
   0.9620219469070435,
   0.9744759798049927,
   0.9758538007736206,
   0.9438536763191223,
   0.9292453527450562,
   0.9207620024681091],
  [0.025280144065618515,
   0.0369177982211113,
   0.2019740790128708,
   0.24003866314888,
   0.003275533439591527,
   0.0014294778229668736,
   0.004902994725853205]],
 'scores': [0.2110863839806761,
  0.23239974491351614,
  0.37333331775312406,
  0.1831805533526836],
 'predict': 2,
 'true': True}

In [57]:
import numpy as np
t = np.array(ner_predict[993]['model_output'])
np.set_printoptions(precision=4)
print(t)

[[0.7827 0.8018 0.672  0.6844 0.8284 0.7786 0.7617]
 [0.983  0.9788 0.5002 0.5091 0.9903 0.9903 0.9903]
 [0.9637 0.962  0.9745 0.9759 0.9439 0.9292 0.9208]
 [0.0253 0.0369 0.202  0.24   0.0033 0.0014 0.0049]]


In [59]:
for i in ner_predict[993]['choices']:
    print(i)

一行书寄千行泪
一封书堕数行泪
一行书信千行泪
寄得一行书信无
